name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        run: |
          npm run build
          mkdir _site
          cp -r fonts _site
          cp -r js _site
          cp index.html _site
      - uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: /actions/deploy-pages@v4
